title:   Preet Desai
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm an undergraduate student at the University of Waterloo, with a keen interest in data analytics and business intelligence.
  <br><br>
  Enthusiastic and motivated personality. Proven ability to work with talented professionals to develop valuable process solutions to meet business objectives. 
  <br><br>
  <a href="https://www.linkedin.com/in/shuchangl/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/profile/shuchang.liang#!/">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/elvisliang/About-Me-Elvis-Liang-3f4f047d65c5438a8d70686f9e849254">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal
